PARAMETERS ordx,orx
PRIVATE GCORREO,GCLAVE,GTITULO,GCONTENIDO,GTEXTBODY
DO correo_resultado_programacion
GCORREO="ips@infasa.net"
GCLAVE="ipsinformatica!@"
GDESTINATARIO='elmerrivera.infasa@gmail.com'
GTITULO='Limite Excedido En Material de Empaque OC # '+ ALLTRIM(ORDX)
GCONTENIDO=""
xasunto='Limite Excedido En Material de Empaque OC # '+ ALLTRIM(ORDX)
PRIVATE xdetalle
xdetalle= ""

SELECT tmptabcorreo
GO TOP 
SCAN 
  TEXT TO lcsql TEXTMERGE NOSHOW 
	<!--detalle 1 -->
	<div style="background-color:transparent;"> <div style="Margin: 0 auto;min-width: 320px;max-width: 1000px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #FFFFFF;" class="block-grid four-up "> <div style="border-collapse: collapse;display: table;width: 100%;background-color:#FFFFFF;">
	<!--[if (mso)|(IE)]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="background-color:transparent;" align="center"> <table cellpadding="0" cellspacing="0" border="0" style="width: 480px;"> <tr class="layout-full-width" style="background-color:#FFFFFF;"><![endif]--><!--[if (mso)|(IE)]> 
	<td align="center" width="120" style=" width:120px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><![endif]--> 
	<div class="col num3" style="max-width: 320px;min-width: 100px;display: table-cell;vertical-align: top;"> <div style="background-color: transparent; width: 100% !important;"> <div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;">
	 <div class=""><!--[if mso]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"><![endif]--> <div style="color:#555555;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;line-height:120%; padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;">
	  <div style="font-size:12px;line-height:14px;color:#555555;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;text-align:left;"> <p style="margin: 0;font-size: 14px;line-height: 17px"><<ALLTRIM(tmptabcorreo.codigo)>></p></div></div><!--[if mso]> </td></tr></table><![endif]--> </div></div></div>
	  </div><!--[if (mso)|(IE)]> </td><td align="center" width="120" style=" width:120px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><![endif]-->
	   <div class="col num3" style="max-width: 320px;min-width: 325px;display: table-cell;vertical-align: top;"> <div style="background-color: transparent; width: 100% !important;"> <div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;">
	    <div class=""><!--[if mso]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"><![endif]--> <div style="color:#555555;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;line-height:120%; padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"> 
	    <div style="font-size:12px;line-height:14px;color:#555555;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;text-align:left;"> <p style="margin: 0;font-size: 12px;line-height: 14px"><<ALLTRIM(tmptabcorreo.nombre)>>
</p></div></div><!--[if mso]> </td></tr></table><![endif]--> </div></div></div></div><!--[if (mso)|(IE)]> </td><td align="center" width="120" style=" width:120px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top">
<![endif]--> <div class="col num3" style="max-width: 320px;min-width: 125px;display: table-cell;vertical-align: top;"> <div style="background-color: transparent; width: 100% !important;"> <div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;"> <div class="">
<!--[if mso]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"><![endif]--> <div style="color:#555555;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;line-height:120%; padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;">
 <div style="font-size:12px;line-height:14px;color:#555555;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;text-align:right;"> <p style="margin: 0;font-size: 12px;line-height: 14px"> <<ALLTRIM(STR(tmptabcorreo.cantidad,12,5))>></p></div></div><!--[if mso]> </td> </tr> </table> <![endif]--> </div> </div> </div> </div> <!--[if (mso)|(IE)]> </td>
 <td align="center" width="120" style=" width:120px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"> <![endif]--> <div class="col num3" style="max-width: 320px;min-width: 125px;display: table-cell;vertical-align: top;">
  <div style="background-color: transparent; width: 100% !important;"> <div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;"> <div class=""> <!--[if mso]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> 
  <td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"><![endif]--> <div style="color:#555555;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;line-height:120%; padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"> <div style="font-size:12px;line-height:14px;color:#555555;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;text-align:right;">
   <p style="margin: 0;font-size: 14px;line-height: 17px"><<ALLTRIM(STR(tmptabcorreo.canrec,12,5))>></p></div></div><!--[if mso]> </td></tr> </table> <![endif]--> </div> </div> </div> </div> <!--[if (mso)|(IE)]> </td> <td align="center" width="120" style=" width:120px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent; 
   border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><![endif]--> <div class="col num3" style="max-width: 320px;min-width: 125px;display: table-cell;vertical-align: top;">
  <div style="background-color: transparent; width: 100% !important;"> <div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;"> <div class=""><!--[if mso]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> 
  <tr> <td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"><![endif]--> <div style="color:#555555;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;line-height:120%; padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"> <div style="font-size:12px;line-height:14px;color:#555555;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;text-align:right;">
   <p style="margin: 0;font-size: 14px;line-height: 17px"><<ALLTRIM(STR(tmptabcorreo.cantt,12,5))>></p></div></div><!--[if mso]> </td> </tr> </table> <![endif]--> </div> </div> </div> </div> <!--[if (mso)|(IE)]> </td>   
   <td align="center" width="120" style=" width:120px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><![endif]-->
    <div class="col num3" style="max-width: 320px;min-width: 125px;display: table-cell;vertical-align: top;"> <div style="background-color: transparent; width: 100% !important;"> <div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;"> <div class=""><!--[if mso]>
     <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"><![endif]--> <div style="color:#555555;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;line-height:120%; padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"> 
     <div style="font-size:12px;line-height:14px;color:#555555;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;text-align:right;"> <p style="margin: 0;font-size: 14px;line-height: 17px"><<ALLTRIM(STR(tmptabcorreo.exede,12,5))>></p></div></div><!--[if mso]> </td> </tr> </table> <![endif]--> </div> </div> </div> </div> <!--[if (mso)|(IE)]> </td>
     <td align="center" width="120" style=" width:120px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><![endif]--> <div class="col num3" style="max-width: 320px;min-width: 75px;display: table-cell;vertical-align: top;">
     <div style="background-color: transparent; width: 100% !important;"> <div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;"> <div class=""><!--[if mso]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> 
     <td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"><![endif]--> <div style="color:#555555;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;line-height:120%; padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"> <div style="font-size:12px;line-height:14px;color:#555555;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;text-align:center;">
      <p style="margin: 0;font-size: 14px;line-height: 17px"><<ALLTRIM(STR(tmptabcorreo.cantfin,12,2))>></p></div></div><!--[if mso]> </td></tr></table><![endif]--> </div></div></div></div><!--[if (mso)|(IE)]> </td></tr></table> </td></tr></table><![endif]--> </div> </div> </div>
	<!--fin detalle 1 -->
  ENDTEXT 
*  </tr> </table> <![endif]--> </div> </div> </div> </div> <!--[if (mso)|(IE)]> </td>
  xdetalle= xdetalle + lcsql
ENDSCAN 
GO TOP 
GTEXTBODY=xdetalle

TEXT TO xtext2 TEXTMERGE NOSHOW 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office"> <head><!--[if gte mso 9]> <xml> <o:OfficeDocumentSettings> <o:AllowPNG/> 
<o:PixelsPerInch>96</o:PixelsPerInch> </o:OfficeDocumentSettings> </xml><![endif]--> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"> <meta name="viewport" content="width=device-width"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <title></title> <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css"> 
<style type="text/css" id="media-query"> body{margin: 0; padding: 0;}table, tr, td{vertical-align: top; border-collapse: collapse;}.ie-browser table, .mso-container table{table-layout: fixed;}*{line-height: inherit;}a[x-apple-data-detectors=true]{color: inherit !important; text-decoration: none !important;}[owa] .img-container div, [owa] .img-container button{display: block !important;}[owa] .fullwidth button{width: 100% !important;}[owa] .block-grid 
.col{display: table-cell; float: none !important; vertical-align: top;}.ie-browser .num12, .ie-browser .block-grid, [owa] .num12, [owa] .block-grid{width: 480px !important;}.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div{line-height: 100%;}.ie-browser .mixed-two-up .num4, [owa] .mixed-two-up .num4{width: 160px !important;}.ie-browser .mixed-two-up .num8, [owa] .mixed-two-up 
.num8{width: 320px !important;}.ie-browser .block-grid.two-up .col, [owa] .block-grid.two-up .col{width: 240px !important;}.ie-browser .block-grid.three-up .col, [owa] .block-grid.three-up .col{width: 160px !important;}.ie-browser .block-grid.four-up .col, [owa] .block-grid.four-up .col{width: 120px !important;}.ie-browser .block-grid.five-up .col, [owa] .block-grid.five-up .col{width: 96px !important;}.ie-browser .block-grid.six-up .col, [owa] 
.block-grid.six-up .col{width: 80px !important;}.ie-browser .block-grid.seven-up .col, [owa] .block-grid.seven-up .col{width: 68px !important;}.ie-browser .block-grid.eight-up .col, [owa] .block-grid.eight-up .col{width: 60px !important;}.ie-browser .block-grid.nine-up .col, [owa] .block-grid.nine-up .col{width: 53px !important;}.ie-browser .block-grid.ten-up .col, [owa] .block-grid.ten-up .col{width: 48px !important;}.ie-browser .block-grid.eleven-up 
.col, [owa] .block-grid.eleven-up .col{width: 43px !important;}.ie-browser .block-grid.twelve-up .col, [owa] .block-grid.twelve-up .col{width: 40px !important;}@media only screen and (min-width: 500px){.block-grid{width: px !important;}.block-grid .col{vertical-align: top;}.block-grid .col.num12{width: 480px !important;}.block-grid.mixed-two-up .col.num4{width: 160px !important;}.block-grid.mixed-two-up .col.num8{width: 320px !important;}.block-grid.two-up 
.col{width: 240px !important;}.block-grid.three-up .col{width: 160px !important;}.block-grid.four-up .col{width: 120px !important;}.block-grid.five-up .col{width: 96px !important;} .block-grid.six-up .col{width: 80px !important;}.block-grid.seven-up .col{width: 68px !important;}.block-grid.eight-up .col{width: 60px !important;}.block-grid.nine-up .col{width: 53px !important;}.block-grid.ten-up .col{width: 48px !important;}.block-grid.eleven-up .col{width: 43px !important;}
.block-grid.twelve-up .col{width: 40px !important;}}@media (max-width: 1000px){.block-grid, .col{min-width: 320px !important; max-width: 100% !important; display: block !important;}.block-grid{width: calc(100% - 40px) !important;}.col{width: 100% !important;}.col > div{margin: 0 auto;}img.fullwidth, img.fullwidthOnMobile{max-width: 100% !important;}.no-stack .col{min-width: 0 !important; display: table-cell !important;}.no-stack.two-up .col{width: 50% !important;}
.no-stack.mixed-two-up .col.num4{width: 33% !important;}.no-stack.mixed-two-up .col.num8{width: 66% !important;}.no-stack.three-up .col.num4{width: 33% !important;}.no-stack.four-up .col.num3{width: 25% !important;}.mobile_hide{min-height: 0px; max-height: 0px; max-width: 0px; display: none; overflow: hidden; font-size: 0px;}}</style> </head> <body class="clean-body" style="margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #e2eace">
 <style type="text/css" id="media-query-bodytag"> @media (max-width: 520px){.block-grid{min-width: 320px!important; max-width: 100%!important; width: 100%!important; display: block!important;}.col{min-width: 320px!important; max-width: 100%!important; width: 100%!important; display: block!important;}.col > div{margin: 0 auto;}img.fullwidth{max-width: 100%!important;}img.fullwidthOnMobile{max-width: 100%!important;}.no-stack .col{min-width: 0!important; 
 display: table-cell!important;}.no-stack.two-up .col{width: 50%!important;}.no-stack.mixed-two-up .col.num4{width: 33%!important;}.no-stack.mixed-two-up .col.num8{width: 66%!important;}.no-stack.three-up .col.num4{width: 33%!important;}.no-stack.four-up .col.num3{width: 25%!important;}.mobile_hide{min-height: 0px!important; max-height: 0px!important; max-width: 0px!important; display: none!important; overflow: hidden!important; font-size: 0px!important;}}
 </style><!--[if IE]> <div class="ie-browser"><![endif]--><!--[if mso]> <div class="mso-container"><![endif]--> <table class="nl-container" style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #e2eace;width: 100%" cellpadding="0" cellspacing="0"> <tbody> <tr style="vertical-align: top"> 
 <td style="word-break: break-word;border-collapse: collapse !important;vertical-align: top"><!--[if (mso)|(IE)]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> <td align="center" style="background-color: #e2eace;"><![endif]--> <div style="background-color:transparent;"> <div style="Margin: 0 auto;min-width: 320px;max-width: 1000px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;" class="block-grid ">
  <div style="border-collapse: collapse;display: table;width: 100%;background-color:transparent;"><!--[if (mso)|(IE)]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="background-color:transparent;" align="center"> <table cellpadding="0" cellspacing="0" border="0" style="width: 480px;"> <tr class="layout-full-width" style="background-color:transparent;"> <![endif]--><!--[if (mso)|(IE)]>
   <td align="center" width="480" style=" width:480px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:0px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><![endif]--> <div class="col num12" style="min-width: 320px;max-width: 1000px;display: table-cell;vertical-align: top;"> <div style="background-color: transparent; width: 100% !important;">
    <div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:0px; padding-right: 0px; padding-left: 0px;"> <div align="center" class="img-container center autowidth fullwidth " style="padding-right: 0px; padding-left: 0px;"><!--[if mso]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr style="line-height:0px;line-height:0px;">
     <td style="padding-right: 0px; padding-left: 0px;" align="center"><![endif]--> <div style="line-height:25px;font-size:1px">&#160;</div><img class="center autowidth fullwidth" align="center" border="0" src="https://d1oco4z2z1fhwp.cloudfront.net/templates/default/20/rounder-up.png" alt="Image" title="Image" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: 0;height: auto;float: none;width: 100%;max-width: 1000px" width="480">
     <!--[if mso]> </td></tr></table><![endif]--> </div></div></div></div><!--[if (mso)|(IE)]> </td></tr></table> </td></tr></table><![endif]--> </div></div></div><div style="background-color:transparent;"> <div style="Margin: 0 auto;min-width: 320px;max-width: 1000px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #FFFFFF;" class="block-grid "> <div style="border-collapse: collapse;display: table;width: 100%;background-color:#FFFFFF;"><!--[if (mso)|(IE)]>
      <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="background-color:transparent;" align="center"> <table cellpadding="0" cellspacing="0" border="0" style="width: 480px;"> <tr class="layout-full-width" style="background-color:#FFFFFF;"><![endif]--><!--[if (mso)|(IE)]> <td align="center" width="480" style=" width:480px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent;
       border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"> <![endif]--> <div class="col num12" style="min-width: 320px;max-width: 1000px;display: table-cell;vertical-align: top;"> <div style="background-color: transparent; width: 100% !important;"> <div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; 
       padding-left: 0px;"> <div align="center" class="img-container center fixedwidth " style="padding-right: 0px; padding-left: 0px;"><!--[if mso]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr style="line-height:0px;line-height:0px;"> <td style="padding-right: 0px; padding-left: 0px;" align="center"><![endif]--> <img class="center fixedwidth" align="center" border="0" src="http://cmfinfasa.net/email/0001.png" alt="Image" title="Image" style="outline: none;text-decoration: 
       none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: 0;height: auto;float: none;width: 100%;max-width: 216px" width="216"><!--[if mso]> </td></tr></table><![endif]--> </div></div></div></div><!--[if (mso)|(IE)]> </td></tr></table> </td></tr></table><![endif]--> </div></div></div><div style="background-color:transparent;"> <div style="Margin: 0 auto;min-width: 320px;max-width: 1000px;overflow-wrap: break-word;word-wrap: break-word;
       word-break: break-word;background-color: #FFFFFF;" class="block-grid "> <div style="border-collapse: collapse;display: table;width: 100%;background-color:#FFFFFF;"><!--[if (mso)|(IE)]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="background-color:transparent;" align="center"> <table cellpadding="0" cellspacing="0" border="0" style="width: 480px;"> <tr class="layout-full-width" style="background-color:#FFFFFF;"><![endif]--><!--[if (mso)|(IE)]> 
       <td align="center" width="480" style=" width:480px; padding-right: 0px; padding-left: 0px; padding-top:0px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><![endif]--> <div class="col num12" style="min-width: 320px;max-width: 1000px;display: table-cell;vertical-align: top;"> <div style="background-color: transparent; width: 100% !important;">
        <div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:0px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;"> <div class=""><!--[if mso]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"><![endif]-->
         <div style="color:#0D0D0D;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;line-height:120%; padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"> <div style="font-size:12px;line-height:14px;color:#0D0D0D;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;text-align:left;"> <p style="margin: 0;font-size: 14px;line-height: 17px;text-align: left"><span style="font-size: 18px; line-height: 18px;">
         <strong><span style="line-height: 26px; font-size: 22px;">Se ha enviado una notificación de los productos que han excedido el 125% del Material De Empaque, OC # :<<ALLTRIM(ordx)>>, OR # : <<ALLTRIM(ORX)>>. </span></strong></span><br></p></div></div><!--[if mso]> </td></tr></table><![endif]--> </div><div align="center" class="img-container center autowidth " style="padding-right: 0px; padding-left: 0px;"><!--[if mso]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr style="line-height:0px;line-height:0px;"> 
         <td style="padding-right: 0px; padding-left: 0px;" align="center"><![endif]--> <img class="center autowidth " align="center" border="0" src="https://d1oco4z2z1fhwp.cloudfront.net/templates/default/20/divider.png" alt="Image" title="Image" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: 0;height: auto;float: none;width: 100%;max-width: 316px" width="316"><!--[if mso]>
          </td></tr></table><![endif]--> </div><table border="0" cellpadding="0" cellspacing="0" width="100%" class="divider " style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 100%;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"> <tbody> <tr style="vertical-align: top"> <td class="divider_inner" style="word-break: break-word;
          border-collapse: collapse !important;vertical-align: top;padding-right: 10px;padding-left: 10px;padding-top: 10px;padding-bottom: 10px;min-width: 100%;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"> <table class="divider_content" height="0px" align="center" border="0" cellpadding="0" cellspacing="0" width="95%" style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;
          mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #BBBBBB;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"> <tbody> <tr style="vertical-align: top"> <td style="word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"> <span>&#160;</span> 
          </td></tr></tbody> </table> </td></tr></tbody> </table> </div></div></div><!--[if (mso)|(IE)]> </td></tr></table> </td></tr></table><![endif]--> </div></div></div><div style="background-color:transparent;"> <div style="Margin: 0 auto;min-width: 320px;max-width: 1000px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #0068A5;" class="block-grid four-up "> <div style="border-collapse: collapse;
          display: table;width: 100%;background-color:#0068A5;"><!--[if (mso)|(IE)]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="background-color:transparent;" align="center"> <table cellpadding="0" cellspacing="0" border="0" style="width: 480px;"> <tr class="layout-full-width" style="background-color:#0068A5;"><![endif]--><!--[if (mso)|(IE)]> <td align="center" width="120" style=" width:120px; padding-right: 0px; padding-left: 0px; padding-top:5px;
           padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><![endif]--> <div class="col num3" style="max-width: 320px;min-width: 100px;display: table-cell;vertical-align: top;"> <div style="background-color: transparent; width: 100% !important;"> <div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; 
           border-right: 0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;"> <div class=""><!--[if mso]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"><![endif]--> <div style="color:#FFFFFF;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;line-height:120%; padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"> 
           <div style="font-size:12px;line-height:14px;color:#FFFFFF;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;text-align:left;"> <p style="margin: 0;font-size: 14px;line-height: 17px"><strong>Código</strong></p></div></div><!--[if mso]> </td></tr></table><![endif]--> </div></div></div></div><!--[if (mso)|(IE)]> </td><td align="center" width="120" style=" width:120px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent; 
           border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><![endif]--> <div class="col num3" style="max-width: 320px;min-width: 325px;display: table-cell;vertical-align: top;"> <div style="background-color: transparent; width: 100% !important;"> <div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; 
           padding-bottom:5px; padding-right: 0px; padding-left: 0px;"> <div class=""><!--[if mso]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"><![endif]--> <div style="color:#FFFFFF;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;line-height:120%; padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"> <div style="font-size:12px;
           line-height:14px;color:#FFFFFF;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;text-align:left;"> <p style="margin: 0;font-size: 12px;line-height: 14px"><strong>Nombre</strong></p></div></div><!--[if mso]> </td></tr></table><![endif]--> </div></div> </div></div> <!--[if (mso)|(IE)]> </td><td align="center" width="120" style=" width:120px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent;
            border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><![endif]--> <div class="col num3" style="max-width: 320px;min-width: 125px;display: table-cell;vertical-align: top;"> <div style="background-color: transparent; width: 100% !important;"> <div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; 
            padding-left: 0px;"> <div class=""><!--[if mso]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"> <![endif]--> <div style="color:#FFFFFF;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;line-height:120%; padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"> <div style="font-size:12px;line-height:14px;
            color:#FFFFFF;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;text-align:center;"> <p style="margin: 0;font-size: 12px;line-height: 14px"><strong>Cantidad</strong></p></div></div><!--[if mso]> </td></tr></table><![endif]--> </div></div></div></div><!--[if (mso)|(IE)]> </td><td align="center" width="120" style=" width:120px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; 
            border-right: 0px solid transparent;" valign="top"><![endif]--> <div class="col num3" style="max-width: 320px;min-width: 125px;display: table-cell;vertical-align: top;"> <div style="background-color: transparent; width: 100% !important;"> <div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;"> <div class="">
            <!--[if mso]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"><![endif]--> <div style="color:#FFFFFF;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;line-height:120%; padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"> <div style="font-size:12px;line-height:14px;color:#FFFFFF;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;text-align:center;"> 
            <p style="margin: 0;font-size: 12px;line-height: 14px">Cantidad Ya Ingresada</p></div></div><!--[if mso]> </td></tr></table><![endif]--> </div></div></div></div><!--[if (mso)|(IE)]> </td><td align="center" width="120" style=" width:120px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"> <![endif]--> 
            <div class="col num3" style="max-width: 320px;min-width: 125px;display: table-cell;vertical-align: top;"><div style="background-color: transparent; width: 100% !important;"><div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;"> <div class=""><!--[if mso]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> 
            <td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"> <![endif]--> <div style="color:#FFFFFF;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;line-height:120%; padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"><div style="font-size:12px;line-height:14px;color:#FFFFFF;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;text-align:center;"> <p style="margin: 0;font-size: 12px;line-height: 14px">Cantidad Recibida</p> </div> </div> <!--[if mso]> 
            </td> </tr></table><![endif]--> </div> </div> </div> </div> <!--[if (mso)|(IE)]> </td> <td align="center" width="120" style=" width:120px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"> <![endif]--> <div class="col num3" style="max-width: 320px;min-width: 125px;display: table-cell;vertical-align: top;"><div style="background-color: transparent; width: 100% !important;">
            <div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;"><div class=""><!--[if mso]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"> <![endif]--> <div style="color:#FFFFFF;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;line-height:120%; 
            padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"> <div style="font-size:12px;line-height:14px;color:#FFFFFF;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;text-align:center;"> <p style="margin: 0;font-size: 12px;line-height: 14px">Excedente</p> </div> </div> <!--[if mso]> </td> </tr></table><![endif]--> </div> </div> </div> </div> <!--[if (mso)|(IE)]> </td> <td align="center" width="120" style=" width:120px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent;
             border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"> <![endif]--> <div class="col num3" style="max-width: 320px;min-width: 75px;display: table-cell;vertical-align: top;"><div style="background-color: transparent; width: 100% !important;"><div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;"> <div class=""><!--[if mso]> 
             <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"> <![endif]--> <div style="color:#FFFFFF;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;line-height:120%; padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"> <div style="font-size:12px;line-height:14px;color:#FFFFFF;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;text-align:center;"> <p style="margin: 0;font-size: 12px;line-height: 14px">% Final</p> </div> 
             </div> <!--[if mso]> </td> </tr></table><![endif]--> </div> </div> </div> </div> <!--[if (mso)|(IE)]> </td> </tr></table> </td></tr></table><![endif]--> </div></div></div><<xdetalle>> <div style="background-color:transparent;"> <div style="Margin: 0 auto;min-width: 320px;max-width: 1000px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #525252;" class="block-grid three-up "> <div style="border-collapse: collapse;display: table;width: 100%;background-color:#525252;"><!--[if (mso)|(IE)]> 
             <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="background-color:transparent;" align="center"> <table cellpadding="0" cellspacing="0" border="0" style="width: 480px;"> <tr class="layout-full-width" style="background-color:#525252;"><![endif]--><!--[if (mso)|(IE)]> <td align="center" width="160" style=" width:160px; padding-right: 0px; padding-left: 0px; padding-top:0px; padding-bottom:0px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top">
             <![endif]--> <div class="col num4" style="max-width: 320px;min-width: 160px;display: table-cell;vertical-align: top;"> <div style="background-color: transparent; width: 100% !important;"> <div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:0px; padding-bottom:0px; padding-right: 0px; padding-left: 0px;"> <div align="center" style="padding-right: 0px; padding-left: 0px; padding-bottom: 0px;" class="">  <div style="line-height:15px;font-size:1px">&#160;</div>
             <div style="display: table; max-width:131px;"><!--[if (mso)|(IE)]> <table width="131" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="border-collapse:collapse; padding-right: 0px; padding-left: 0px; padding-bottom: 0px;" align="center"> <table width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse; mso-table-lspace: 0pt;mso-table-rspace: 0pt; width:131px;"> <tr> <td width="32" style="width:32px; padding-right: 5px;" valign="top"><![endif]--> 
             <table align="left" border="0" cellspacing="0" cellpadding="0" width="32" height="32" style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;Margin-right: 5px"> <tbody> <tr style="vertical-align: top"> <td align="left" valign="middle" style="word-break: break-word;border-collapse: collapse !important;vertical-align: top"> <a href="#" title="Facebook" target="_blank">
              <img src="http://cmfinfasa.net/email/facebook@2x.png" alt="Facebook" title="Facebook" width="32" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important"> </a> <div style="line-height:5px;font-size:1px">&#160;</div></td></tr></tbody> </table><!--[if (mso)|(IE)]> </td><td width="32" style="width:32px; padding-right: 5px;" valign="top"><![endif]--> 
              <table align="left" border="0" cellspacing="0" cellpadding="0" width="32" height="32" style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;Margin-right: 5px"> <tbody> <tr style="vertical-align: top"> <td align="left" valign="middle" style="word-break: break-word;border-collapse: collapse !important;vertical-align: top"> <a href="#" title="Twitter" target="_blank"> 
              <img src="http://cmfinfasa.net/email/twitter@2x.png" alt="Twitter" title="Twitter" width="32" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important"> </a> <div style="line-height:5px;font-size:1px">&#160;</div></td></tr></tbody> </table><!--[if (mso)|(IE)]> </td><td width="32" style="width:32px; padding-right: 0;" valign="top">
               <![endif]--> <table align="left" border="0" cellspacing="0" cellpadding="0" width="32" height="32" style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;Margin-right: 0"> <tbody> <tr style="vertical-align: top"> <td align="left" valign="middle" style="word-break: break-word;border-collapse: collapse !important;vertical-align: top"> <a href="#" title="Google+" target="_blank"> 
               <img src="http://cmfinfasa.net/email/googleplus@2x.png" alt="Google+" title="Google+" width="32" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important"> 
 </a> <div style="line-height:5px;font-size:1px">&#160;</div></td></tr></tbody> </table><!--[if (mso)|(IE)]> </td></tr></table> </td></tr></table><![endif]--> </div></div></div></div></div><!--[if (mso)|(IE)]> </td><td align="center" width="160" style=" width:160px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top">
 <![endif]--> </div><!--[if (mso)|(IE)]> </td><td align="center" width="160" style=" width:160px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"> <![endif]--> <div class="col num4" style="max-width: 320px;min-width: 160px;display: table-cell;vertical-align: top;"> <div style="background-color: transparent; width: 100% !important;"> 
 <div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;"> <div class=""><!--[if mso]> <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="padding-right: 0px; padding-left: 0px; padding-top: 20px; padding-bottom: 0px;"><![endif]--> <div style="color:#a8bf6f;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;line-height:120%;
  padding-right: 0px; padding-left: 0px; padding-top: 20px; padding-bottom: 0px;"> <!--[if mso]> </td></tr></table><![endif]--> </div></div></div></div><!--[if (mso)|(IE)]> </td></tr></table> </td></tr> </table><![endif]--> </div></div></div><div style="background-color:transparent;"> <div style="Margin: 0 auto;min-width: 320px;max-width: 1000px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;" class="block-grid "> <div style="border-collapse: collapse;display: table;width: 100%;background-color:transparent;"><!--[if (mso)|(IE)]> 
  <table width="100%" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="background-color:transparent;" align="center"> <table cellpadding="0" cellspacing="0" border="0" style="width: 480px;"> <tr class="layout-full-width" style="background-color:transparent;"> <![endif]--><!--[if (mso)|(IE)]> <td align="center" width="480" style=" width:480px; padding-right: 0px; padding-left: 0px; padding-top:0px; padding-bottom:5px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><![endif]-->
   <div class="col num12" style="min-width: 320px;max-width: 1000px;display: table-cell;vertical-align: top;"> <div style="background-color: transparent; width: 100% !important;"> <div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:0px; padding-bottom:5px; padding-right: 0px; padding-left: 0px;"> <div align="center" class="img-container center autowidth fullwidth " style="padding-right: 0px; padding-left: 0px;"> <!--[if mso]> <table width="100%" cellpadding="0" cellspacing="0" border="0">
    <tr style="line-height:0px;line-height:0px;"> <td style="padding-right: 0px; padding-left: 0px;" align="center"><![endif]--> <img class="center autowidth fullwidth" align="center" border="0" src="https://d1oco4z2z1fhwp.cloudfront.net/templates/default/20/rounder-dwn.png" alt="Image" title="Image" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: 0;height: auto;float: none;width: 100%;max-width: 1000px" width="480"> <!--[if mso]> </td></tr></table><![endif]--> </div>
    <table border="0" cellpadding="0" cellspacing="0" width="100%" class="divider " style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 100%;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"> <tbody> <tr style="vertical-align: top"> <td class="divider_inner" style="word-break: break-word;border-collapse: collapse !important;vertical-align: top;padding-right: 30px;padding-left: 30px;padding-top: 30px;padding-bottom: 30px;min-width: 100%;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"> 
    <table class="divider_content" align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 0px solid transparent;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"> <tbody> <tr style="vertical-align: top"> <td style="word-break: break-word;border-collapse: collapse !important;vertical-align: top;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"> <span></span> </td></tr></tbody> </table> </td></tr></tbody> </table>
     </div></div></div><!--[if (mso)|(IE)]> </td></tr></table> </td></tr></table><![endif]--> </div></div></div><!--[if (mso)|(IE)]> </td></tr></table><![endif]--> </td></tr></tbody> </table><!--[if (mso)|(IE)]> </div><![endif]--> </body></html> 
 ENDTEXT
_cliptext=xtext2

CLEAR
LOMAIL = NEWOBJECT("Cdo2000", "Cdo2000.fxp")
WITH LOMAIL
	.CSERVER = "smtp.gmail.com"
	.NSERVERPORT = 25 &&465
	.LUSESSL = .T.
	.NAUTHENTICATE = 1
	.CUSERNAME = GCORREO
	.CPASSWORD = GCLAVE
	.CFROM = GCORREO
	.CTO = GDESTINATARIO
	.CSUBJECT = GTITULO
	.CHTMLBODY = XTEXT2
	.CTEXTBODY = GTEXTBODY
	.cBCC = "javier.flores@infasa.net"
ENDWITH
IF LOMAIL.SEND() > 0
	LOCAL IERRORES
	STORE '' TO IERRORES
	FOR I=1 TO LOMAIL.GETERRORCOUNT()
		IERRORES=IERRORES+ LOMAIL.GETERROR(I)
	ENDFOR
	IF 'NOT AVAILABLE'$UPPER(IERRORES)
		MESSAGEBOX('No se pudo enviar el Correo, Usuario o Contraseña Incorrecta.',0+16+0,'Error')
	ELSE
		MESSAGEBOX('No se pudo enviar el Correo.  '+CHR(13)+CHR(13)+IERRORES,0+16+0,'Error')
	ENDIF
	LOMAIL.CLEARERRORS()
	RETURN .F.
ELSE
	LOMAIL.CLEARERRORS()
	WAIT WINDOW "Corren enviado correctamente" TIMEOUT 1
	RETURN .T.
ENDIF